apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: assisted-teacher-workspace
  namespace: assisted-teacher
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
