apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: emma-portfolio-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: emma-portfolio
      images:
        - alias: emma-portfolio
          imageName: ghcr.io/emmatf/my_portfolio
          commonUpdateSettings:
            pullSecret: pullsecret:argocd/emma-portfolio-ghcr-login-secret
            updateStrategy: newest-build
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"
    gitConfig:
      branch: main
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: emma-portfolio-github-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /github/e
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: emma-portfolio-ghcr-login-secret
      secretNamespace: argocd
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner