apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: jujudb-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: jujudb
      images:
        - alias: jujudb
          imageName: "ghcr.io/bapttf/jujudb"
          commonUpdateSettings:
            updateStrategy: semver
            pullSecret: pullsecret:argocd/bapttf-ghcr-login-secret
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"
    gitConfig:
      branch: main
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: bapttf-github-secrets
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /github/b
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: bapttf-ghcr-login-secret
      secretNamespace: argocd
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner
