apiVersion: argocd-image-updater.argoproj.io/v1alpha1
kind: ImageUpdater
metadata:
  name: vaultwarden-updater
  namespace: argocd
spec:
  applicationRefs:
    - namePattern: vaultwarden-workload
      images:
        - alias: vaultwarden
          imageName: "vaultwarden/server:1.x"
          commonUpdateSettings:
            updateStrategy: semver
  writeBackConfig:
    method: "git:secret:argocd/argocd-image-updater-git-creds"
    gitConfig:
      branch: "main"
      pullRequest:
        github: {}
