apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: github-secrets
  namespace: emma-portfolio
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /github/e
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: ghcr-login-secret
      secretNamespace: emma-portfolio
      secretType: kubernetes.io/dockerconfigjson
      creationPolicy: Owner
---
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: basic-auth-secrets
  namespace: emma-portfolio
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /portfolio
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: portfolio-basic-auth
      secretNamespace: emma-portfolio
      secretType: Opaque
      creationPolicy: Owner