apiVersion: v1
kind: Service
metadata:
  name: camofox
  labels:
    app: camofox
spec:
  selector:
    app: camofox
  ports:
    - protocol: TCP
      port: 9377
      targetPort: http
      name: http
