apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  instances: 1
  imageName: ghcr.io/tensorchord/cloudnative-vectorchord:17
  storage:
    size: 10Gi
    storageClass: local-path
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: "1"
      memory: 2Gi
  postgresql:
    shared_preload_libraries:
      - "vchord.so"
  backup:
    barmanObjectStore:
      destinationPath: s3://cnpg-backups/
      endpointURL: https://e16df4d29f7d54d2f57456402bebd130.r2.cloudflarestorage.com
      s3Credentials:
        accessKeyId:
          name: cnpg-r2-credentials
          key: AWS_ACCESS_KEY_ID
        secretAccessKey:
          name: cnpg-r2-credentials
          key: AWS_SECRET_ACCESS_KEY
      wal:
        compression: gzip
      data:
        compression: gzip
    retentionPolicy: "30d"
  managed:
    roles:
      - connectionLimit: -1
        ensure: present
        inherit: true
        name: immich
        login: true
        superuser: true
        passwordSecret:
          name: immich-db-secret
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: immich-db
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  name: immich
  owner: immich
  cluster:
    name: immich-postgres
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
    - name: earthdistance
      ensure: present
    - name: cube
      ensure: present
