apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: immich-db-credentials-cnpg
  namespace: cnpg-system
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /immich/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: immich-db-secret
      secretNamespace: cnpg-system
      secretType: Opaque
      creationPolicy: Owner
