apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: postgres-cluster-daily-backup
  namespace: cnpg-system
spec:
  cluster:
    name: postgres-cluster
  schedule: "0 0 4 * * *"
  backupOwnerReference: self
  immediate: true
---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-postgres-daily-backup
  namespace: cnpg-system
spec:
  cluster:
    name: immich-postgres
  schedule: "0 30 4 * * *"
  backupOwnerReference: self
  immediate: true
