---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-db-credentials
  namespace: infisical
spec:
  encryptedData:
    password: AgCng/Yl8esD73Gg6sVYnpaXUfeeUqOrdtPgQ1wng7LeJ7LZQSiBIqfqcfFLm5j/3xlkRfgjj3IN05Uo3vIlWxm/YzGupTSMob7KFAZdRfP9eM3d00KrmIi1DO3T6LG6/FLCkqtTHUqAJo00d2VbkYDcAWThRKBN8llZSOPwFDks/uYoxV7eG2FAvYkV27ZPDJkDws6UD3mVyr9rmP4Kz2TgffK6/MVbWrPARZs7HkFUcVZ+gE3VROoMLk+n5u0iJGXOmDJhSqRy57RrXnCTEzLwcykXTJTXaZLPsGphs/88sKFBRJXHkAZNvZD/K5zHtxgf7ahroeJKVCC50/LOyxuUIbkMl5TQjS0elq6FP/o0vwusbVCOdX9RqRumBTUNGZ4CwvV51DIJLiAAeh4k/5XH6diVUqeq6JkUhVK9gzbhAHWujS+Z/gwVaEPzk74O2xqDpP+SxtGeDqNyU0x0sikKkm7ox6miZx6bRdUSriTcI0+wPFSOI4lFJyAV6++Wlb4KsGRiCAZ8k0hQ8n+qVSZOji82Gn/KE/f1vEnYZ6gFB7Pwme5CAshZDxQ2In2A261RpZnHsvYFk3/JBZqPmd2WyCvto72+oK2A+DliTFP8pWQ+e2RcoxzpuWVIT6YwUEIn0AdX5DKoElmL7UQm4otqbTUVDZj49Gnfbg6xV1SwqVskJv16Bylp0YN4cjsb5YARH4eGtM1uTw==
    username: AgAIMfnZxlhXkSiMBpskVCS4/YH4bh4VdWrFr+osN8Rdf4lb5mPNZDPxXIHSL16J+rv+xfwv6wtXpr0ZxNrfUfsOEoD63MkQS2Fhfi/3K6/wd+exMv7ZF/NMUd28tQ3sLZuUxoEgUFVrjRhLV/DT+/uu+NgwTqEf5wNzfAsNWZVCviL/NKHVPENBkLloThXx7NGzRyRMg9ZH05Flo4UUhBZRDhtgXRGiDAY+kqoZg2FUdlcsnNT4C92LrFwL242q9uJrYaWQqvA4lD6APR6jZ7pf8gfbUaXTxnRBnWgpEBcunRVQ0nGweN18ieYSsVUArpe+ACEpQDiJwqLmuq4GHW9QGUjuuCkS0s13OkOjRg6TIQVBQHW0JC6CPcBLDdYvYlQ9qfJZ1CXWHkjpXM893RRtv8NqqiM496v31mxRqXjFHXLMVgU1g7iSMD4grgXdM9ZdUwzLS1uK/ZommN1L2TYc9H8746aGvyzfCJo3l/CjjUd+L8S2M9/T3USOMcqkKBTmgAK23JxgOObZ5A3qR49KQwb6VRbsPAlHkf2PM7HGesuFJNwg6mZGVNk4aYdwojY9POexekb7ntIYX+pzvNDgzbvxe3dPEWCQDqR0hLEVSPQ3HjIk9lfboppVsJ7ZiQjGiGU7qcFGS6kiV5hnsyGL+Ejxai0aIO3yefaTmWe4nynlI0Yrvf67RZhWw9k+rWgBwh+bflvTuR8=
  template:
    metadata:
      name: infisical-db-credentials
      namespace: infisical
    type: Opaque
