apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: couchdb-infisical-sync
  namespace: couchdb
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /couchdb
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: couchdb
      secretNamespace: couchdb
      secretType: Opaque
      creationPolicy: Owner