apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: bifrost-infisical-secret
  namespace: openclaw
  annotations:
    argocd.argoproj.io/sync-wave: "-1" 
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure 
        envSlug: prod
        secretsPath: /agents/bifrost 
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: bifrost-secret 
      secretNamespace: openclaw
      secretType: Opaque
      creationPolicy: Owner