apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configMapGenerator:
  - name: hermes-lya-filebrowser-config
    files:
      - config.yaml
resources:
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
