apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: sickgnal
commonLabels:
  app: sickgnal-server
resources:
  - infisical-secret.yaml
  - certificate.yaml
  - deployment.yaml
  - service.yaml
  - ingressroutetcp.yaml
configMapGenerator:
  - name: sickgnal-config
    literals:
      - DB_DRIVER=postgres
      - DB_HOST=postgres-cluster-rw.cnpg-system.svc.cluster.local
      - DB_PORT=5432
      - DB_USER=sickgnal
      - DB_NAME=sickgnal
      - DB_SSLMODE=disable
      - PORT=8080
