apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cours-cert
  namespace: openclaw
spec:
  secretName: cours-tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "cours.bapttf.com"
