---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-universal-auth
  namespace: tailscale
spec:
  encryptedData:
    clientId: AgB0MUOkje7oBP2joIGZno+2HrDRSHtMmazpIPHf4YzQfvAgs16Mwem96N/u7zvvaFt3IopA3ofsO4R8obcDaawMCAca1OVInwgI8somgtStQtTwJz6UVt0qJoRNVIJaVBduwN4mxMG2po3hz0pai1dDavTbJoz98SV+KsrcJGz6Xj0VC+ter7mkageSwqjSYlONGl23kbYUZw0s7O/s9ktFgNB8xc6uhqBuLOg6BpRYsY8t92ATxjmBCtVVLNv+uJ73RkybQcF+kNZkyCEYAAiuU3YEpI9bIjoT9G+kOYlvxF36PHLmVRD2Bw2BkCVXuBx/51z3pVMszWvmSEhj6E5/23SjPDLshy7pclnDVbrICym+ZEIghGkQyJIRYzBP4scdPtQiqeAStn4Op6pTO/hJboNTmxOfhsh0dMo4ADDfUf+NgZPmB0SU6HPuOdiFx7CZgOO1G4hSeXeK0m8KhIq3ROMTTebvmk+lyprteLv2hJ3ojIdauTna9uLSP26w/u/SFCM5Jp27zLHPEAqfHEcMAKDqK9z3loyQxM01cbPCXx6Rdmo7k94Qw+mzID+durqQe+/jkW9ViWCL7cTPca0chvf3EzbjgUQ0M5rtjCp48eImNBKsp2hoJ/uQPpmnsmXUthGWpkepY7AqMRcYE8y7xZsohyTxrZ4Yaxn0QSp3qVpqHRGQZD/T3sKfa2SY8k0=
    clientSecret: AgALIr3lwnWkvGkXH2/klSpDsrkYKdYpVA6eEyOBykJHfUAdjJH3RcnEdIEgdGUW9n5Ge9Y1BmI4vAnANOO1aJS/qGTnARx9TdUNOr96FqKIPSa5Tu+VM/54uq6iEsoR8aRVKWrI4w3Vp1YJduGAbzRpvRbFwDnTqfrXTeqwvL8YaEGfliiUOK0EmV5e8MKc4aKIJQJlX/6Tk6Kp/fkQ6sdYdvnJJZ+RqAOhULj9/IA2O2BlL1rzcoHwvU3YyFej1zGZQFUFemiS8eooqsRphK1Xta8YCxTU20N9pixnI9GvKkviDsTmBw0zrewkE4rETqQrFCRPvcM7wwyVnXYg0IZn7aRX+UdV3LFnOyAOcNdvTR6gxzCjtDJwpEIWDKFRrIBIc8pKuPuesrglTR3zz5xcHVZbzsEY6nhc5//BiSyg/7uFAlOAQgDPu1XsrXJ+gG6pS13G03aJDDxdTZy6v+u00K5vakh6RW8Jo4R8Tw7NfjBOpMRT+mpmGXsH1gpxog4/rfTHDLJiL8Ma3JgG4H7ZjllmOxhQBvHr+VPxmaMDfHvHTmsUMAxl7nTnqzaBQBYH8a2cDVPT1fK33Tez70dvMkDTtiMsYFzMt3cFHGvWPHosXK/G1OXbCqXn7IcmQU5yk/gXQqpzVW7+051YEE76ZOsgrPo6pjf3AxPTxfo3lTlFQ5m+Xf6/u3Ab0u6IgzA=
  template:
    metadata:
      name: infisical-universal-auth
      namespace: tailscale
