---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: infisical-universal-auth
  namespace: infisical
spec:
  encryptedData:
    clientId: AgBWoGYCW23d45q1nMJ/Vd6vT5ZphPLWMszwwLAKLTqNwP00FjkLa2mZCmPCO9pJEL/Ofcl35juonQqmi671omg61hyCdU7LbOHg/sMfa8f9cyC+3GtauRi0zxmy3MczRrVjrEVyfEV/z5q5CKFiLByatVHqKg2d+LcMSSSxWbkPse1w5UZDmZFOUdDw2GkQNgUGCRfLNb2m0eFsOfkcPdrHEGIahieFQQeaqmjA+kJ0uWgE9ctuDRWEXPnRtq73JQVdy6Phqf70TETnYdayFMNBlqcrDKS7L2Vx6D1TNoQMQovcavgMz5A2fe8Tw5TytX8t9UdK9wNxV3t0ah45cmozc1zhJuIQIlqSSYXpemK2lHphp1z64UxWX0s6EAyLBqELpsw5Gsot4Mv3l2zE23TqSsuZYJCl0rD2XaK+DQ/JfwFJRI+OyYB++zOU5I5afc6u0cf82ajiL9mHI8EI/1pk+qwV463i2NXzwTb3Rsxnn8qTrtLWgfAE8q/52ob3EjDvKEYlQtbl0ycMy4A7QCNYlnkI/5z0Rp+JK/OzkNcU6ITGnEMogrsx1zbGelcrIsb8gE5+Lv3QDMIsomw0R9wBJQPYLJS9U+siESDoTW4v1QD3LTLzBNZol/l1SCBKIDWGS1kto/DkZjfvhnE3e1Vt4is6Wrivgt8FUMtAxtpAQ/Fm5MocgPuODfbH4dbe6qU=
    clientSecret: AgDJJNiCiZLdPcJHQ/ItLM9tXXn9JpM67y2FCiA7g5DtzxHUmxfn5qUTg3HYQSdWbId9zIMlMxzvblnwqwg1Elyb0I3oTjTsuZ9K8gAyzkDqcApf34v/lm4q7ZPcqwDfg3TgmBQVs32ofQlCBrtnhV58hSWRRDEsIFkPWm8TfMGJCHklZuuhYMdgoLH8eg1ecGhv+GziTTwXLxr7SCNEJvOdbUuqN+eDYLDjVD3tBDOU9fT6P1IKQBJRWbpHt0pZwpsFV/ETFY6kjz8Usr06V2jp7NWQBcK7tCnNI+cfjGFqhjkGmsipe+YQXSdWsnCp27R6bqaaDFAAPfmgwxUAnfl4vnyhQ9+Likh/uh2K+RUkXE06DItKJ7Tsw9T28BTZMgE007w5VpiuO6O37FE/7BTM0TwER7YewrpQpNQch3g+YRYHM2sC+IQBo002bfRHTBRzjJivsckTBguXRSRN0oix/jcj+gs9puVI7V+BI7uurlbI3vCaau6Z3I34E/uwKL7NE2OV/qXdRw0sLRw4oHZluSSSMf8c70SM/488qpBtxsYqAfE8taeYHYznkrO5qUMvArrtMdeCJsJTMbzntK3zup7SrXXd9/cEr/PmgUKQgzdeVKRoMze8dbXLtzB3p3bVK2gYuhl7J5tY0XS/do6Ejgx08ibOQbJAOr1erWI1RKCTCBU3eecNWsIqaUKVk5o=
  template:
    metadata:
      name: infisical-universal-auth
      namespace: infisical
