apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ce-analytics-secret-sync
spec:
  hostAPI: https://infisical.bapttf.com/api
  resyncInterval: 60
  authentication:
    universalAuth:
      secretsScope:
        envSlug: prod
        secretsPath: /ce-analytics
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical
  managedSecretReference:
    secretName: ce-analytics-secret
    secretNamespace: ce-analytics
    creationPolicy: Owner
