apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: ce-analytics-secret-sync
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /ce-analytics
      credentialsRef:
        secretName: infisical-machine-identity
        secretNamespace: infisical
  managedSecretReference:
    secretName: ce-analytics-secret
    secretNamespace: ce-analytics
    secretType: Opaque
    creationPolicy: Owner
