apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ce-analytics

resources:
  - namespace.yaml
  - certificate.yaml
  - infisical-secret.yaml
  - agent-deployment.yaml
  - app-deployment.yaml
  - service.yaml
  - ingressroute.yaml
