apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fabron-cert
  namespace: fabron
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "fabron.bapttf.com"
