apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: meilisearch-credentials
  namespace: meilisearch
  annotations:
    argocd.argoproj.io/sync-wave: "-1" # Creates the secret before Meilisearch deploys
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /meilisearch # Update path here
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: meilisearch-master-key # This is the K8s secret it will generate
      secretNamespace: meilisearch
      secretType: Opaque
      creationPolicy: Owner