apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: velero-credentials-sync
  namespace: velero
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /velero
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: velero-r2-credentials
      secretNamespace: velero
      secretType: Opaque
      creationPolicy: Owner
