apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: minio-credentials-sync
  namespace: minio
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /minio
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: minio-credentials # MinIO will look for this exact name
      secretNamespace: minio
      secretType: Opaque
      creationPolicy: Owner