apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gowa-storage
  namespace: gowa
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
  storageClassName: local-path
