apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
  namespace: immich
  labels:
    app: immich
    component: machine-learning
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: immich
      component: machine-learning
  template:
    metadata:
      labels:
        app: immich
        component: machine-learning
    spec:
      containers:
        - name: machine-learning
          image: ghcr.io/immich-app/immich-machine-learning:v2
          ports:
            - containerPort: 3003
              name: http
          envFrom:
            - configMapRef:
                name: immich-config
          volumeMounts:
            - name: model-cache
              mountPath: /cache
          readinessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            tcpSocket:
              port: http
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          resources:
            requests:
              cpu: 250m
              memory: 1Gi
            limits:
              cpu: "2"
              memory: 3Gi
      volumes:
        - name: model-cache
          persistentVolumeClaim:
            claimName: immich-machine-learning-cache
