apiVersion: v1
kind: PersistentVolume
metadata:
  name: immich-storagebox
  annotations:
    pv.kubernetes.io/provisioned-by: smb.csi.k8s.io
spec:
  capacity:
    storage: 1Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: immich-storagebox
  mountOptions:
    - dir_mode=0775
    - file_mode=0664
    - uid=1000
    - gid=1000
    - vers=3.1.1
    - cache=strict
    - noserverino
    - mfsymlinks
  csi:
    driver: smb.csi.k8s.io
    volumeHandle: immich-storagebox
    volumeAttributes:
      source: //u619007-sub1.your-storagebox.de/u619007-sub1
    nodeStageSecretRef:
      name: immich-storagebox-secret
      namespace: immich
