apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: recettes-cert
  namespace: recettes
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "recettes.bapttf.com"
