apiVersion: v1
kind: Service
metadata:
  name: recettes
  namespace: recettes
  labels:
    app: recettes
spec:
  selector:
    app: recettes
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
