apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

configMapGenerator:
  - name: filebrowser-config
    files:
      - config.yaml

resources:
  - data-pvc.yaml
  - deployment.yaml
  - service.yaml
  - certificate.yaml
  - ingressroute.yaml
