use_default_settings: true

server:
  bind_address: "0.0.0.0"
  port: 8080
  limiter: false

search:
  formats:
    - html
    - json
  safe_search: 2

outgoing:
  proxies:
    http: http://nas-proxy.openclaw.svc.cluster.local:3128
    https: http://nas-proxy.openclaw.svc.cluster.local:3128
  request_timeout: 10
