apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: immich-cert
  namespace: immich
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "immich.bapttf.com"
