apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: openclaw-ssh-cert
  namespace: openclaw
spec:
  secretName: tls-certificate 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - "ssh.bapttf.com"