apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bapttf-front-cert
  namespace: bapttf-front
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "bapttf.com"
