apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gowa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: workloads/gowa
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gowa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
