apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lldap
  namespace: argocd
  annotations:
    argocd.argoproj.io/manifest-generate-paths: .
spec:
  project: system
  source:
    repoURL: 'https://github.com/BaptTF/vps-infra.git'
    targetRevision: HEAD
    path: system/lldap
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: lldap
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
