apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://helm.traefik.io/traefik
    targetRevision: 32.1.1
    chart: traefik
    helm:
      values: |
        ingressClass:
          enabled: true
          isDefaultClass: true
        
        providers:
          kubernetesCRD:
            enabled: true
          kubernetesIngress:
            enabled: true
            publishedService:
              enabled: true
        
        ports:
          web:
            redirectTo:
              port: websecure
          websecure:
            tls:
              enabled: true
        
        ingressRoute:
          dashboard:
            enabled: true
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true