apiVersion: apps/v1
kind: Deployment
metadata:
  name: compreface-admin
  namespace: compreface
  labels:
    app: compreface
    component: admin
spec:
  revisionHistoryLimit: 2
  replicas: 1
  selector:
    matchLabels:
      app: compreface
      component: admin
  template:
    metadata:
      labels:
        app: compreface
        component: admin
    spec:
      containers:
        - name: admin
          image: exadel/compreface-admin:1.2.0
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: POSTGRES_URL
              value: "jdbc:postgresql://postgres-cluster-rw.cnpg-system.svc.cluster.local:5432/frs"
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: compreface-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: compreface-db-credentials
                  key: password
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"
            - name: ADMIN_JAVA_OPTS
              value: "-Xmx256m"
            - name: EXTERNAL_API_HOST
              value: "http://compreface-api:8080"
            - name: SPRING_MAIL_HOST
              value: ""
            - name: MANAGEMENT_HEALTH_MAIL_ENABLED
              value: "false"
            - name: ADMIN_EMAIL
              valueFrom:
                secretKeyRef:
                  name: compreface-secret
                  key: ADMIN_EMAIL
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: compreface-secret
                  key: ADMIN_PASSWORD
          resources:
            requests:
              cpu: "50m"
              memory: "384Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 120
            periodSeconds: 30
            failureThreshold: 5
