apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: compreface-db-credentials
  namespace: compreface
spec:
  hostAPI: https://app.infisical.com/api
  authentication:
    universalAuth:
      secretsScope:
        projectSlug: infrastructure
        envSlug: prod
        secretsPath: /compreface/db
      credentialsRef:
        secretName: infisical-universal-auth
        secretNamespace: infisical
  managedKubeSecretReferences:
    - secretName: compreface-db-credentials
      secretNamespace: compreface
      secretType: Opaque
      creationPolicy: Owner
