apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: compreface

resources:
  - core-deployment.yaml
  - core-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  - ui-deployment.yaml
  - ui-service.yaml
  - ingress-tailscale.yaml
  - infisical-secret.yaml
