apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compreface-db
  namespace: compreface
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 5Gi
