apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: camille-recettes
  namespace: camille-recettes
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`camille-recettes.bapttf.com`)
      kind: Rule
      services:
        - name: camille-recettes
          port: 80
  tls:
    secretName: tls-certificate
