apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ha-eyg-cert
spec:
  secretName: tls-certificate
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - "eyguians.bapttf.com"
