apiVersion: apps/v1
kind: Deployment
metadata:
  name: lacoope-frontend
  namespace: lacoope
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lacoope-frontend
  template:
    metadata:
      labels:
        app: lacoope-frontend
    spec:
      containers:
        - name: frontend
          image: git.bapttf.com/bapttf/lacoopefrontend:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: PUBLIC_API_BASE_URL
              value: "https://lacoope-api.bapttf.com/v1"
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 40
            periodSeconds: 30
            timeoutSeconds: 10
            failureThreshold: 3
---
apiVersion: v1
kind: Service
metadata:
  name: lacoope-frontend
  namespace: lacoope
spec:
  selector:
    app: lacoope-frontend
  ports:
    - port: 3000
      targetPort: 3000
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: lacoope-frontend-ingress
  namespace: lacoope
spec:
  entryPoints:
    - websecure
  routes:
    - match: Host(`lacoope.bapttf.com`)
      kind: Rule
      services:
        - name: lacoope-frontend
          port: 3000
  tls: {}